# Generated by Django 5.2 on 2025-04-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_portfolio", "0003_workexperience_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="app_portfolio.projects",
            ),
        ),
    ]
