# Generated by Django 5.2 on 2025-04-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_portfolio", "0004_alter_workexperience_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectKeyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_features",
                        to="app_portfolio.projects",
                    ),
                ),
            ],
        ),
    ]
