# Generated by Django 4.0 on 2025-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_projectkeyfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='app_portfolio.Skills'),
        ),
    ]
